site_name: path-comment-hook
site_description: Pre-commit hook that adds file path headers to source code
site_author: Shourya Maheshwari
site_url: https://shouryamaheshwari.github.io/path-comment-hook
repo_url: https://github.com/shouryamaheshwari/path-comment-hook
repo_name: shouryamaheshwari/path-comment-hook

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.action.edit
    - content.action.view
    - navigation.expand
    - navigation.path
    - navigation.prune
    - toc.integrate

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: shouryamaheshwari
      repo: path-comment-hook
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
      - getting-started/installation.md
      - getting-started/quick-start.md
      - getting-started/why-path-headers.md
  - User Guide:
      - user-guide/cli-usage.md
      - user-guide/pre-commit-setup.md
      - user-guide/configuration.md
      - user-guide/file-types.md
      - user-guide/examples.md
  - Advanced:
      - advanced/performance.md
      - advanced/custom-formats.md
      - advanced/monorepos.md
      - advanced/ci-integration.md
  - API Reference: api/reference.md
  - Contributing:
      - contributing/development.md
      - contributing/testing.md
      - contributing/architecture.md
  - troubleshooting.md
  - faq.md
  - changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shouryamaheshwari/path-comment-hook
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/path-comment-hook/

copyright: Copyright &copy; 2024 Shourya Maheshwari
