# .github/workflows/release.yml

name: Release to PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  id-token: write  # Required for trusted publishing to PyPI

jobs:
  test-before-release:
    name: Pre-release Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: "1.8.3"
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Run tests
      run: |
        poetry run pytest tests/ --cov=path_comment --cov-report=term-missing

    - name: Run linting
      run: |
        poetry run ruff check .
        poetry run mypy src/path_comment tests

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: test-before-release
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: "1.8.3"
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Extract version from tag
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=${GITHUB_REF#refs/tags/}
        fi
        echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
        echo "tag=${VERSION}" >> $GITHUB_OUTPUT

    - name: Update version in pyproject.toml
      run: |
        poetry version ${{ steps.version.outputs.version }}

    - name: Build package
      run: |
        poetry build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ steps.version.outputs.version }}
        path: dist/

    - name: Test package installation
      run: |
        pip install dist/*.whl
        path-comment-hook --version
        path-comment-hook welcome

  publish-test-pypi:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-${{ needs.build.outputs.version }}
        path: dist/

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true

  test-testpypi-installation:
    name: Test TestPyPI Installation
    runs-on: ubuntu-latest
    needs: [build, publish-test-pypi]
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Wait for TestPyPI availability
      run: |
        echo "Waiting 2 minutes for TestPyPI to update..."
        sleep 120

    - name: Install from TestPyPI
      run: |
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ path-comment-hook==${{ needs.build.outputs.version }}

    - name: Test installation
      run: |
        path-comment-hook --version
        path-comment-hook --help

    - name: Test basic functionality
      run: |
        echo "print('hello')" > test.py
        path-comment-hook test.py
        grep -q "# test.py" test.py || (echo "Path comment not added!" && exit 1)
        echo "TestPyPI installation test passed!"

  publish-pypi:
    name: Publish to PyPI (Manual Approval Required)
    runs-on: ubuntu-latest
    needs: [build, test-testpypi-installation]
    # environment: production-release  # Configure this environment in GitHub repo settings for manual approval
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-${{ needs.build.outputs.version }}
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://upload.pypi.org/legacy/
        verbose: true



  test-installation:
    name: Test PyPI Installation
    runs-on: ${{ matrix.os }}
    needs: publish-pypi
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.11"]
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Wait for PyPI availability
      run: |
        echo "Waiting 2 minutes for PyPI to update..."
        sleep 120

    - name: Install from PyPI
      run: |
        pip install path-comment-hook==${{ needs.build.outputs.version }}

    - name: Test installation
      run: |
        path-comment-hook --version
        path-comment-hook --help
        path-comment-hook welcome

    - name: Test basic functionality
      run: |
        echo "print('hello')" > test.py
        path-comment-hook test.py
        grep -q "# test.py" test.py || (echo "Path comment not added!" && exit 1)
        echo "Installation test passed on ${{ matrix.os }} with Python ${{ matrix.python-version }}"
